### ISSUE TITLE
3.0.2

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#840]
> 已发。

发布一周来，发现并改了不少 bug ，列在下面，等这几个简单的 bug 全部改完后发一个 3.0.2 版本。

其他功能上的大改动都放到 3.1.0 中做。
- [x] 修复一个 spm doc watch 时报错的问题。https://github.com/spmjs/spmjs.io/issues/24
- [x] 简化了 spm init 的模板。
- [x] 修复 output 其他类型文件（png、swf 等）时报错的问题。#838
- [x] 修复 init 有时没有生成 .gitignore 的问题。#832
- [x] 修复 spm build -O 的指定输出目录在当前目录之外时报错的问题。#823
- [x] 优化了代理安装 phantomjs 的逻辑。 #822
- [x] install 出现偶发的乱码问题。https://github.com/spmjs/spmjs.io/issues/30 @sorrycc 
- [x] 修复 spm doc pubish 发布文档时，spm.ignore 字段仍然生效的问题。https://github.com/spmjs/spm/commit/b99836f0de6dbe7a025e6ceddf2fe217e2093046
- [x] 修复 include=all 时 ignore 不生效的问题。#835 要等这个 https://github.com/popomore/umi/pull/4 发布。@popomore
- [x] spm3 打包时 main 不支持缺省 `.js` 后缀。等 popomore/father#3 发布。#843
